version: '3.8'

services:
  backend:
    image: seavthay/ems-backend:latest
    container_name: ems-backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DEBUG=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=EMSDB
      - DB_USER=postgres
      - DB_PASSWORD=emsProjectFinal
      - DB_HOST=database-ems.c96qsmskwzwb.ap-southeast-2.rds.amazonaws.com
      - DB_PORT=5432

  frontend:
    image: seavthay/ems-frontend:latest
    container_name: ems-frontend
    ports:
      - "80:3000"
    restart: always
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=production
    depends_on:
      - backend