version: '3.8'

services:
  backend:
    image: seavthay/ems-backend:latest
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DEBUG=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=EMSDB
      - DB_USER=postgres
      - DB_PASSWORD=emsProjectFinal
      - DB_HOST=database-ems.c96qsmskwzwb.ap-southeast-2.rds.amazonaws.com
      - DB_PORT=5432

services:
  frontend:
    image: seavthay/ems-frontend:latest
    ports:
      - "80:3000"
    restart: always