apiVersion: v1
kind: ConfigMap
metadata:
  name: ems-config
  namespace: ems
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DB_ENGINE: django.db.backends.postgresql
  DB_HOST: ems-postgres
  DB_PORT: "5432"
  DB_NAME: ems_db
  DB_USER: postgres
  VITE_API_BASE_URL: http://localhost:8000
