apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ems-postgres-data
  namespace: ems
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-postgres
  namespace: ems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems-postgres
  template:
    metadata:
      labels:
        app: ems-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ems-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: ems-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ems-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: ems-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: ems-postgres
  namespace: ems
spec:
  selector:
    app: ems-postgres
  ports:
    - port: 5432
      targetPort: 5432
