apiVersion: v1
kind: Secret
metadata:
  name: ems-secret
  namespace: ems
type: Opaque
stringData:
  SECRET_KEY: change-this-secret-key-before-real-deploy
  DB_PASSWORD: change-this-database-password
