# Generated by Django 6.0.5 on 2026-05-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_alter_leave_options_alter_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('maternity', 'Maternity Leave'), ('emergency', 'Emergency Leave'), ('unpaid', 'Unpaid Leave')], max_length=50),
        ),
    ]
