# Generated by Django 6.0.5 on 2026-05-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('maternity', 'Maternity Leave'), ('emergency', 'Emergency Leave'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], max_length=50),
        ),
    ]
